### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by A11en0** [Songkeys/bing-chat#3]
![image](https://user-images.githubusercontent.com/33925232/218114201-4be99957-2901-43ff-8baf-de02d5cf7cf5.png)

**Comment by Songkeys** [comment]
May I know the reproduction steps?

**Comment by A11en0** [comment]
Prompt: could you please give me a news summary?

**Comment by Bohan-J** [comment]
Same: 
![image](https://user-images.githubusercontent.com/52446949/218115321-7609b848-fee7-421b-80eb-227a8156006b.png)

**Comment by A11en0** [comment]
Cool, it has been fixed, thanks for your great work!!!

**Comment by Songkeys** [comment]
Great. I'm working on improving the UI so there might be some breaking changes. Let me know about what I can improve! Happy chatting.

**Comment by A11en0** [comment]
Sure, Bing chat seems smarter than ChatGPT, thanks for your efforts to take it for us.
