### ISSUE TITLE
cors error in dev environment

### ISSUE THREAD

**Issue by zjrwtx** [Songkeys/bing-chat#4]
![image](https://user-images.githubusercontent.com/86822589/218143425-548732a2-61ad-46d1-bb78-eb82f4878cfd.png)

**Comment by Songkeys** [comment]
It's saying 524 error. looks like a timeout issue. I think it's because my server is under heavy. I just restarted it. It should work now.

**Comment by Songkeys** [comment]
It's "banned". See https://github.com/Songkeys/bing-chat/issues/5#issuecomment-1426119004

**Comment by zjrwtx** [comment]
all right，i waitting for your new updating,thanks

**Comment by songkeys** [comment]
I use my account in the backend now. It's alive.
